#!/bin/bash
set -e

# Install s2i
go get github.com/openshift/source-to-image
pushd ${GOPATH}/src/github.com/openshift/source-to-image
export PATH=$PATH:${GOPATH}/src/github.com/openshift/source-to-image/_output/local/bin/linux/amd64/
hack/build-go.sh
popd

# Install docker-squash
wget https://github.com/jwilder/docker-squash/releases/download/v0.2.0/docker-squash-linux-amd64-v0.2.0.tar.gz
sudo tar -C /usr/local/bin -xzvf docker-squash-linux-amd64-v0.2.0.tar.gz

# Docker login
docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" quay.io

for i in */
do
  if [[ ${i%*/} != 'test' ]]; then

    version=${i%*/}
    image=quay.io/$TRAVIS_REPO_SLUG:$version

    docker build -t $image $version/
    docker save $image | sudo /usr/local/bin/docker-squash | docker load
    IMAGE_NAME=$image ./$version/test/run
    docker push $image
  fi
done

docker tag $image quay.io/$TRAVIS_REPO_SLUG:latest
docker push quay.io/$TRAVIS_REPO_SLUG:latest
