#!/bin/bash
source cgroup-limits

set -o pipefail
set -eu
# Include hidden files
shopt -s dotglob

# Set the umask to be '002' so that any files/directories created from
# this point are group writable.
umask 002

function rake_assets_precompile() {
  [[ "$DISABLE_ASSET_COMPILATION" == "true" ]] && return
  [ ! -f Gemfile ] && return
  [ ! -f Rakefile ] && return
  ! grep " rails " Gemfile.lock >/dev/null && return
  ! grep " execjs " Gemfile.lock >/dev/null && return
  ! bundle exec 'rake -T' | grep "assets:precompile" >/dev/null && return

  echo "---> Starting asset compilation ..."
  bundle exec rake assets:precompile
}

export RACK_ENV=${RACK_ENV:-"production"}

function is_puma_installed() {
  [ ! -f Gemfile.lock ] && return 1
  grep ' puma ' Gemfile.lock >/dev/null
}
