#!/bin/bash
source cgroup-limits

set -e
set -o pipefail

# Include hidden files
shopt -s dotglob

# Set the umask to be '002' so that any files/directories created from
# this point are group writable.
umask 002

function rake_assets_precompile() {
  [[ "$DISABLE_ASSET_COMPILATION" == "TRUE" ]] && return
  [ ! -f Gemfile ] && return
  [ ! -f Rakefile ] && return
  ! grep " rake " Gemfile.lock >/dev/null && return
  ! bundle exec 'rake -T' | grep "assets:precompile" >/dev/null && return

  echo "---> Starting asset compilation ..."
  bundle exec rake assets:precompile
}

function is_puma_installed() {
  [ ! -f Gemfile.lock ] && return 1
  grep ' puma ' Gemfile.lock >/dev/null
}

export RACK_ENV=${RACK_ENV:-"production"}
export RAILS_ENV=${RAILS_ENV:-"production"}

# Overwrite ENV when DEBUG==TRUE
if [ "$DEBUG" == "TRUE" ]; then
  RACK_ENV="development"
  RAILS_ENV="development"
fi
