sudo: required
matrix:
  include:
  - services:
    - docker
    env: VARIANTS=default
before_install:
# Install s2i
- |
  go get github.com/openshift/source-to-image
  pushd ${GOPATH}/src/github.com/openshift/source-to-image
  export PATH=$PATH:${GOPATH}/src/github.com/openshift/source-to-image/_output/local/bin/linux/amd64/
  hack/build-go.sh
  popd
script:
- if [ "$TRAVIS_BRANCH" = "master" ]; then export DOCKER_PUSH=true && docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" quay.io; fi
- ./hack/run build
notifications:
  slack:
    secure: b6PdUr8ybgzeYdspTM1Y8xrv6hS72/bSIKVcp9Hw412lqDd+KzdpSNIXMZkzj08n7lXPP8G8aCUf4dldDI7FIdt2cNGkLIOf/EGMajzC8B95x5F/3vFzx9xM0NzMGwDHOleRd9+tj7ENP3eq9CcBkcqDNmMHgODImxNcYvxG01DvN+Qn3gNN5nGvCVtDHyNtzsLeryR15z60UjuoLVyjw0LD7unZSyfQT48cyi+MEGeX1394VTwUjkZQFSdrZfRbZeGcZESGTISQeBWreZ0xO/gqJCAJCNjTcgPYDQCtAKsSKe3x5ilAo8LxzFzdSkWEKGze9yPgDBXwwpjf9zdf3Uj3EdmvcqzFodR/1pVePalARYBPmLaGbcRfeuW8XvcUNN2Z1FwR1b/xXzPadxTElk0L6w9lKYsX+x7CY2PpUhF80oRhWeRwgUslgybvP3ehjGDFroMDAinVBjycYUsbVO3lFw2pISYmCD6Xxiath2bbWF/qsalOhz87JzXnVS8Q+IbPlW2roM46Omh5asNJpexqWI/SIVs+jJImkxNM4R2Uq7POMLUbNPuJn0Wz0ZH1+yLxEAJZR3jHs0Vq3xiU9NGfBjagXj/Fdq0ZAdsVP3o3QM6zV15FTPi4u2YNoOJBdzzGFUhbcx8YC1SIpK0ctpcaHrwJ56Bj54X6Dxqiyns=
env:
  global:
  - secure: eh04N9g+C2nEZIhl5gMQdun22M/ufTexvPKpD+8zFQSCNWQSmqLReaaMusbHyCtYQGrImVNhxm5OmQ2mKJl+8bW/K/UEBgO+oIers63kvVUsiu2g97zQdHSnJAO658Qq41Kq/3DoKc7mzfIX0kGiB0ewMBYHkAa6imFrlyiTYLZPDmMVjnmyOWe7PWoR9+ou+BHIyFTYXOvbVf23NfJvozB+XcMptXMQMMqF0Xeaz4/UnpG5W/Gdkd/WbmTv+F2aECCtj3OPKv5/FWoUMZRxq+k4BFC8tO4D15tD5flzKFQWSYq/NBk8RpewCc/7kNcQ9jt56B/PPmAug6NdOsHogjcnbkvdqFW4pzpLygpS6SX8DOqD6n0mjxMZSrZTpply/QKDqdNRAeuyTPGxmNloYNB/UUTJRfj3WVwALYY2vDyXeekRRyQH+hhiEvgkmUef4qIguf5I0j3oX69IgfmUjDeMIPqzRU1SnUxynkJ58C4AyvtIYr7glcD1teO/V+5dIOTSya1iFgg2wld09/TqzioX76klAoUXGFHz0CqIUpktTC1bYAvLIzbOjrdiXB3c9LIQkqnL/FclF0H2GutkmCarjjIhvjkUSZGQCxraY8z0WwcrBR/VOMKjvHz7+zjb9VCj1RtH8Ajs70gMlzOZpiRgCwUAwnectHQoV3C+ZUs=
  - secure: BRxCIuGZDSa/1LDK6c4R2dm8/gyhSbBf8na/77bMi8daJslyWt8PESx3OYv6Tt/looEtk6L0Wt61PaBOUYPKcmE6GLAGjZYaT6tF0gB1CRJjUMRmAAumC0BrsRK+Pu5R/S2lcpWJtq0JfKIDlj1l4L7pH0eCOsbGBX9w1bak/FFWVun+ixi/6xdJennIdDDCZSvZA7btOgMM/r4mLxs+7saaiTcSEgp5JJJfOgEf9uDMXp8ua8OG8AUhxgPaa3qnP0CXI023rQoCKGLu+hVNEJ5JB6I5f9xx3FWv+ykEchkkFnjkV/DP/MFZgJQbTGfeauGsNPjyb0H7WVaEuSqH5gJIJikE+52cz1f1QxBUjZeCZQLGuUekDWf2piuWr1F7vChr9ytbruvHLS++5mB2TMBrfiXAakrwFxe+dOep02fFC6VIY+xNxuDHhkkx3qSzm4oO2RLBGQT0ZRjPeC+nIuzzpNz4KBFVTt3Iyq9nScz+Uq9arPtEMvh3+9FYX7qUpEHC2MFZMIN10vzMxQFQMSPzBSgxqUW+Gn8uUwpfygND5kvCb5/7F/BMvumtVNupF/O2+XdtLoPQY7i9W/Wro+wTT6AuWRHs571VA5k95TNuW8V/ft9zgjL4l8ABXucrfBDrpR/ooU9vUWkt41RXWfFZcu47D5iIu2dijvTjWhw=
