RUN apt-get update && apt-get install -y --no-install-recommends \
      build-essential \
      libxml2-dev \
      libpq5 \
      libpq-dev \      
      libmysqlclient18 \
      libmysqlclient-dev && \
    rm -rf /var/lib/apt/lists/*
