#!/bin/bash

NAME="ruby"
DISPLAY_NAME="Ruby"
REPO="ausnimbus/s2i-ruby"
TEMPLATES="pre,s2i,template,post"
VARIANT="alpine"
VERSIONS="2.1,2.2,2.3,2.4"

DOCKER_PUSH=${DOCKER_PUSH:-"false"}

if [ $# -ne 1 ]; then
    echo "Usage: ./hack/run [build,update]"
    exit
fi

if [ "$1" == "build" ]; then
  source $(readlink -zf $(dirname "${BASH_SOURCE[0]}"))/../common/hack/run
fi

if [ "$1" == "update" ]; then
  source $(readlink -zf $(dirname "${BASH_SOURCE[0]}"))/../common/hack/update
fi
