#!/bin/bash

NAME="ruby"
DISPLAY_NAME="Ruby"
TYPE="s2i"
VARIANT="alpine"
VERSIONS="2.1,2.2,2.3,2.4"

DOCKER_PUSH=${DOCKER_PUSH:-"false"}

source $(readlink -zf $(dirname "${BASH_SOURCE[0]}"))/../common/hack/run
